<?php
	/**
	* display help addtohome_and module information
	*/
	function addtohome_help($path,$arg){
		$output = '';
		switch($path){
			case "admin/help#addtohome":
				$output = '<p>'.t("Create a too").'</p>'; //fixme
			break;
		}
		return $output;
	}

	/**
		giving permissions
	*/
	function addtohome_perm(){
		return array('administer addtohome settings'); 
	}


	function addtohome_admin(){
		//array of file fids in order to use it in gettinf file's object
		$file_fids = variable_get('addtohome_icons', array( 
	      'addtohome_ios_icon'          => NULL,
	      'addtohome_ios_iphone_retina' => NULL,
	      'addtohome_ios_ipad_icon'     => NULL,
	      'addtohome_ios_ipad_retina'   => NULL,
	      'addtohome_andr_icon'         => NULL,
    	));
		$form = array();
		$form['addtohome_app_name'] = array(
			'#type'           => 'textfield',
			'#title'          => t('Application name'),
			'#default_value'  => variable_get('addtohome_app_name','Application'),
			'#size'           => 13,
			'#weight'         => 1,
			'#max_length'     => 11,
			'#description'    => t('The name of application which user will see by default. It can be changed (max 11 letters)'), 
			'#required'=>TRUE,
		);
		$form['addtohome_ios']=array(
			'#type'      	=> 'fieldset',
			'#title'	 	=> t('Ios settings'),
			'#weight'		=> 5,
			'#collapsible'	=> TRUE,
			'#collapsed'	=> FALSE,
		);
			
			$form['addtohome_ios']['addtohome_display_times'] = array(
				'#type' 			=> 'textfield',
				'#title'			=> t('Absolute maximum number of times the message will be shown to the user'),
				'#default_value'	=> variable_get('addtohome_display_times',0), 
				'#size'				=> 13,
				'#max_length'		=> 10,
				'#element_validate'	=> array('addtohome_check_num'),
				'#description' 		=> t("0: no limit"),
				'#required'			=> TRUE,

			);
			$form['addtohome_ios']['addtohome_actions'] = array(
				'#type' 		=> 'checkbox',
				'#title'		=> t('Forbid actions'),
				'#default_value'=> variable_get('addtohome_actions',0),
				'#description' 	=> t('Forbid any actions before user closes window'), 
				'#required'		=> TRUE,
			);
			$form['addtohome_ios']['addtohome_second_time'] = array(
				'#type' 		=> 'checkbox',
				'#title'		=> t('Show window on second page load'),
				'#default_value'=> variable_get('addtohome_second_time',0),
				'#description' 	=> t('By default user sees window when enter the site first time'),
				'#required'		=> TRUE,
			);
			$form['addtohome_ios']['addtohome_show_after'] = array(
				'#type' 			=> 'textfield',
				'#title'			=> t("Delay before message will appear"),
				'#default_value'	=> variable_get('addtohome_show_after',1),
				'#size'				=> 13,
				'#max_length'		=> 10,
				'#required'			=> TRUE,
				'#element_validate'	=> array('addtohome_check_num'),
			);
			$form['addtohome_ios']['addtohome_lifespan'] = array(
				'#type' 			=> 'textfield',
				'#title'			=> t('How many seconds window lives if user doesn\'t close it'),
				'#default_value'	=> variable_get('addtohome_lifespan',20),
				'#size'				=> 13,
				'#max_length'		=> 10,
				'#required'			=> TRUE,
				'#element_validate'	=> array('addtohome_check_num'),
			);
			$form['addtohome_ios']['addtohome_display_pace'] = array(
				'#type' 			=> 'textfield',
				'#title'			=> t('Minutes before the message is shown again'),
				'#default_value'	=> variable_get('addtohome_display_pace',1440),
				'#size'				=> 13,
				'#max_length'		=> 10,
				'#description' 		=> t('0: display every time, default 24 hours'),
				'#required'			=> TRUE,
				'#element_validate'	=> array('addtohome_check_num'),
			);
			$form['addtohome_ios']['addtohome_message'] = array(
				'#type' 		=> 'textfield',
				'#title'		=> t('Message'),
				'#default_value'=> variable_get('addtohome_message',t('You can add a bookmark to you home screen')),
				'#size'			=> 60,
				'#max_length'	=> 60,
				'#description' 	=> t('What will user see on this tooltip (max 60 letters)'),
				'#required'		=> TRUE,


			);
			$form['addtohome_ios']['addtohome_detect'] = array(
				'#type' 			=> 'checkbox',
        		'#title' 			=> t('Detect bookmark on homescreen'),
				'#description'		=> t('Try to detect if the site has been added to the homescreen'), 
				'#default_value'	=> variable_get('addtohome_detect',0), //FIXME
			);
			$form['addtohome_ios']['addtohome_ios_icon']=array(
				'#type' => 'file',
				'#title'=> t('An icon which user will see in messag'),
			);
			//if file was uploaded
			if ($file_fids['addtohome_ios_icon']){
				$file = _get_file_path($file_fids['addtohome_ios_icon']);
				$form['addtohome_ios']['addtohome_ios_icon_link'] = array(
					'#value' => l(	t('Current icon'), 
									file_create_url($file->filepath),
									array('attributes'=> array('target'=> '_blank','external'=> TRUE))
								),
				);
				$form['addtohome_ios']['delete_addtohome_ios_icon']=array(
					'#type' 		=> 'checkbox',
					'#title'		=> t("Delete this icon"),
					'#default_value'=> variable_get('delete_addtohome_ios_icon',0),
				);
				if(module_exists("imagecache")){
					$form['addtohome_ios']['addtohome_ios_icon']['#suffix'] = '<div>' . theme('imagecache', 'thumbnail', $file->filepath) . '</div>';
				}
			}
			
			$form['addtohome_ios']['addtohome_ios_ipad_icon']=array(
				'#type' 		=> 'file',
				'#title'		=> t("Ipad icon"),
				'#description' 	=> '76x76',
			);
			//if file was uploaded
			if ($file_fids['addtohome_ios_ipad_icon']){
				$file = _get_file_path($file_fids['addtohome_ios_ipad_icon']);
				$form['addtohome_ios']['addtohome_ios_ipad_icon_link'] = array(
					'#value' => l(	t('Current icon'), 
                					file_create_url($file->filepath),
                					array('attributes'=>array('target' => '_blank', 'external' => TRUE))
                				),
				);
				$form['addtohome_ios']['delete_addtohome_ios_ipad_icon']=array(
					'#type' 		=> 'checkbox',
					'#title'		=> t("Delete this icon"),
					'#default_value'=> variable_get('delete_addtohome_ios_ipad_icon',0),
				);
				if(module_exists("imagecache")){
					$form['addtohome_ios']['addtohome_ios_ipad_icon']['#suffix'] = '<div>' . theme('imagecache', 'thumbnail', $file->filepath) . '</div>';
				}
			}


			$form['addtohome_ios']['addtohome_ios_iphone_retina']=array(
				'#type' 		=> 'file',
				'#title'		=> t('iPhone retina icon'),
				'#description' 	=> '120x120',
			);
			//if file was uploaded
			if ($file_fids['addtohome_ios_iphone_retina']){
				$file = _get_file_path($file_fids['addtohome_ios_iphone_retina']);
				$form['addtohome_ios']['addtohome_ios_iphone_retina_link'] = array(
					'#value' => l(	t('Current icon'), 
									file_create_url($file->filepath),
									array('attributes'=>array('target'=>'_blank','external'=>TRUE))
								),
				);
				$form['addtohome_ios']['delete_addtohome_ios_iphone_retina']=array(
					'#type' => 'checkbox',
					'#title'=>t("Delete this icon"),
					'#default_value'=>variable_get('delete_addtohome_ios_iphone_retina',0),
				);
				if(module_exists("imagecache")){
					$form['addtohome_ios']['addtohome_ios_iphone_retina']['#suffix'] = '<div>' . theme('imagecache', 'thumbnail', $file->filepath) . '</div>';
				}
			}


			$form['addtohome_ios']['addtohome_ios_ipad_retina']=array(
				'#type' => 'file',
				'#title'=>t("Ipad retina"),
				'#description' => "152x152",
			);
			//if file was uploaded
			if ($file_fids['addtohome_ios_ipad_retina']){
				$file = _get_file_path($file_fids['addtohome_ios_ipad_retina']);
				$form['addtohome_ios']['addtohome_ios_ipad_retina_link'] = array(
					'#value' => l(t('Current icon'), file_create_url($file->filepath),array('attributes'=>array('target'=>'_blank','external'=>TRUE))),
				);
				
				if(module_exists("imagecache")){
					$form['addtohome_ios']['addtohome_ios_ipad_retina']['#suffix'] = '<div>' . theme('imagecache', 'thumbnail', $file->filepath) . '</div>';
				}
				$form['addtohome_ios']['delete_addtohome_ios_ipad_retina']=array(
					'#type' 		=> 'checkbox',
					'#title'		=>t('Delete this icon'),
					'#default_value'=>variable_get('delete_addtohome_ios_ipad_retina',0),
				);
			}


		$form['addtohome_ios_use_msgbox']=array(
			'#type'    		=> 'checkbox',
			'#weight'		=> 4,
			'#title'		=> t('Make analogous message for IOS as in Android'),
			'#default_value'=> variable_get('addtohome_ios_use_msgbox',0),
			'#description' 	=> t('By default the tooltip points to a button of adding bookmark in IOS'),
		);

		$form['addtohome_android']=array(
			'#type'  		=> 'fieldset',
			'#title'		=> t('Android settings'),
			'#weight'		=> 3,
			'#collapsible'	=> TRUE,
			'#collapsed'	=> FALSE,
		);
			$form['addtohome_android']['addtohome_andr_message']=array( //FIXME utilizeaza addtohome_android in loc de addtohome_andr
				'#type' 		=> 'textfield',
				'#title'		=> t("Message to appear"),
				'#default_value'=> variable_get('addtohome_andr_message',t('Install our application from Google Play')), 
				'#size'			=> 60,
				'#max_length'	=> 60,
			);
			$form['addtohome_android']['addtohome_andr_link']=array(
				'#type' 		=>'textfield',
				'#title'		=> t('Link to Google Play'), 
				'#default_value'=> variable_get('addtohome_andr_link','https://play.google.com/store/apps/details?id=deeplace.md'),
				'#size'			=> 60,
				'#max_length'	=> 60,

			);
			$form['addtohome_android']['addtohome_show_one_time']=array(
				'#type'    		=> 'checkbox',
				'#title'		=> t('Show only one time if user closes the window'),
				'#default_value'=> variable_get('addtohome_show_one_time',0),
				'#description' 	=> t('Works only if user has cookies enabled.'),
			);
			$form['addtohome_android']['addtohome_andr_icon']=array( 
				'#type' => 'file',
				'#title'=> t('An icon which user will see in message'),
			);
			//if file was uploaded
			if ($file_fids['addtohome_andr_icon']){

				$file = _get_file_path($file_fids['addtohome_andr_icon']);
				$form['addtohome_android']['addtohome_andr_icon_link'] = array(
					'#value' => l(	t('Current icon'), 
									file_create_url($file->filepath),
									array('attributes'=>array('target'=>'_blank','external'=>TRUE))
								),
				);
				
				if(module_exists("imagecache")){
					$form['addtohome_android']['addtohome_andr_icon']['#suffix'] = '<div>' . theme('imagecache', 'thumbnail', $file->filepath) . '</div>';
				}
				$form['addtohome_android']['delete_addtohome_andr_icon']=array(
					'#type' 		=> 'checkbox',
					'#title'		=> t('Delete this icon'),
					'#default_value'=> variable_get('delete_addtohome_andr_icon',0),
				);
			}
		$form['#attributes'] = array('enctype' => "multipart/form-data");
		$form['#submit'][] = 'addtohome_submit';
			 
		return system_settings_form($form);
	}

function addtohome_menu(){
	$items = array();
	$items['admin/settings/addtohome'] = array(
		'title' 			=> 'Add to home screen module',
		'description' 		=> 'Module creates a tooltip for mobile bookmarks', 
		'page callback' 	=> 'drupal_get_form',
		'page arguments' 	=> array('addtohome_admin'),
		'access arguments' 	=> array('administer addtohome settings'), 
		'type'				=> MENU_NORMAL_ITEM,

	);
	return $items;
}

function addtohome_admin_validate($form, &$form_state){
	// file_save_upload
	$name_dir = "addtohome";  
	$dir = file_directory_path() . DIRECTORY_SEPARATOR . $name_dir;
		
	$file_fids = variable_get('addtohome_icons', array(
    	'addtohome_ios_icon'          => NULL,
	    'addtohome_ios_iphone_retina' => NULL,
	    'addtohome_ios_ipad_icon'     => NULL,
	    'addtohome_ios_ipad_retina'   => NULL,
	    'addtohome_andr_icon'         => NULL,
    ));
	
	if(file_check_directory($dir, FILE_CREATE_DIRECTORY)){
		
		//delete file according to user request
		if($form_state['values']['delete_addtohome_ios_icon'] == 1 && $file_fids['addtohome_ios_icon']){
			$filepath =  _get_file_path($file_fids['addtohome_ios_icon'])->filepath;
			file_delete($filepath);
			// put value of NULL in order not to obtain image
			$file_fids['addtohome_ios_icon'] = NULL;
			//turn the flag of delete to 0
			$form_state['values']['delete_addtohome_ios_icon'] = 0;


		}
		if($form_state['values']['delete_addtohome_ios_ipad_icon'] == 1 && $file_fids['addtohome_ios_ipad_icon']){
			$filepath =  _get_file_path($file_fids['addtohome_ios_ipad_icon'])->filepath;
			file_delete($filepath);
			$file_fids['addtohome_ios_ipad_icon'] = NULL;
			$form_state['values']['delete_addtohome_ios_ipad_icon'] = 0;
			

		}
		if($form_state['values']['delete_addtohome_ios_ipad_retina'] == 1 && $file_fids['addtohome_ios_ipad_retina']){
			$filepath =  _get_file_path($file_fids['addtohome_ios_ipad_retina'])->filepath;
			file_delete($filepath);
			$file_fids['addtohome_ios_ipad_retina'] = NULL;
			$form_state['values']['delete_addtohome_ios_ipad_retina'] = 0;

		}
		if($form_state['values']['delete_addtohome_ios_iphone_retina'] == 1 && $file_fids['addtohome_ios_iphone_retina']){
			$filepath =  _get_file_path($file_fids['addtohome_ios_iphone_retina'])->filepath;
			file_delete($filepath);
			$file_fids['addtohome_ios_iphone_retina'] = NULL;
			$form_state['values']['delete_addtohome_ios_iphone_retina'] = 0;

		}
		if($form_state['values']['delete_addtohome_andr_icon'] == 1 && $file_fids['addtohome_andr_icon']){
			$filepath =  _get_file_path($file_fids['addtohome_andr_icon'])->filepath;
			file_delete($filepath);
			$file_fids['addtohome_andr_icon'] = NULL;
			$form_state['values']['delete_addtohome_andr_icon'] = 0;

		}


		$current_file = file_save_upload('addtohome_ios_icon',array(),$dir);
		if($current_file){
			file_set_status($current_file, FILE_STATUS_PERMANENT);
			
			if ($file_fids['addtohome_ios_icon']) {
				//delete file
				$filepath =  _get_file_path($file_fids['addtohome_ios_icon'])->filepath;
				file_delete($filepath);
			}
			drupal_write_record('files', $current_file, 'fid');
			$file_fids['addtohome_ios_icon'] = $current_file->fid;
		}
		
		$current_file = file_save_upload('addtohome_ios_ipad_icon',array(),$dir);
		if($current_file){
			file_set_status($current_file, FILE_STATUS_PERMANENT);
			drupal_write_record('files', $current_file, 'fid');
			if ($file_fids['addtohome_ios_ipad_icon']) {
				//delete file 
				$filepath =  _get_file_path($file_fids['addtohome_ios_ipad_icon'])->filepath;
				file_delete($filepath);	
			}

			$file_fids['addtohome_ios_ipad_icon'] = $current_file->fid;
		}

		$current_file = file_save_upload('addtohome_ios_ipad_retina',array(),$dir);
		if($current_file){
			file_set_status($current_file, FILE_STATUS_PERMANENT);
			drupal_write_record('files', $current_file, 'fid');
			if ($file_fids['addtohome_ios_ipad_retina']) {
				//delete file 
				$filepath =  _get_file_path($file_fids['addtohome_ios_ipad_retina'])->filepath;
				file_delete($filepath);	
			}
			$file_fids['addtohome_ios_ipad_retina'] = $current_file->fid;
		}

		$current_file = file_save_upload('addtohome_ios_iphone_retina',array(),$dir);
		if($current_file){
			file_set_status($current_file, FILE_STATUS_PERMANENT);
			drupal_write_record('files', $current_file, 'fid');
			if ($file_fids['addtohome_ios_iphone_retina']) {
				//delete file 
				$filepath =  _get_file_path($file_fids['addtohome_ios_iphone_retina'])->filepath;
				file_delete($filepath);
				
			}
			$file_fids['addtohome_ios_iphone_retina'] = $current_file->fid;
		}

		$current_file = file_save_upload('addtohome_andr_icon',array(),$dir);
		if($current_file){
			file_set_status($current_file, FILE_STATUS_PERMANENT);
			drupal_write_record('files', $current_file, 'fid');
			if ($file_fids['addtohome_andr_icon']) {
				//delete file 
				$filepath =  _get_file_path($file_fids['addtohome_andr_icon'])->filepath;
				file_delete($filepath);
				
			}
			$file_fids['addtohome_andr_icon'] = $current_file->fid;
		} 
	}
	
	variable_set('addtohome_icons', $file_fids); //FIXME

	if(!valid_url($form_state['values']['addtohome_andr_link'])){
		form_set_error('addtohome_andr_link' ,t("You have entered an incorrect link"));
	}
}


function addtohome_init(){
	
		$path = drupal_get_path('module','addtohome');
		//get path to images
		$image_fids = variable_get('addtohome_icons',array( 
	      'addtohome_ios_icon'          => NULL,
	      'addtohome_ios_iphone_retina' => NULL,
	      'addtohome_ios_ipad_icon'     => NULL,
	      'addtohome_ios_ipad_retina'   => NULL,
	      'addtohome_andr_icon'         => NULL,
    	));

		$image_paths = array();
		//$array_files = _get_multiple_file_path($image_fids);
		
		if($image_fids){ 
			$image_paths = _get_multiple_file_path($image_fids);
		}
		
		//adding meta tags for images 
		//in drupal 7 drupal_add_html_head
		drupal_set_html_head('<meta name="apple-mobile-web-app-title" content="'.variable_get('addtohome_app_name','Application').'">');
		drupal_set_html_head(addMeta($image_paths['addtohome_ios_icon'],'0'));
		drupal_set_html_head(addMeta($image_paths['addtohome_ios_ipad_icon'],'76'));
		drupal_set_html_head(addMeta($image_paths['addtohome_ios_iphone_retina'],'120'));
		drupal_set_html_head(addMeta($image_paths['addtohome_ios_ipad_retina'],'152'));
		
  		
  		drupal_set_html_head('<meta name="apple-mobile-web-app-capable" content="yes" />');
  		drupal_set_html_head('<meta name="mobile-web-app-capable" content="yes" />');
				
		
	if(drupal_is_front_page()){	
		//create an array of settings to send it o js
		$my_settings = array(
			'addtohome_app_name' 		=> variable_get('addtohome_app_name','Application'),
			'addtohome_display_times' 	=> variable_get('addtohome_display_times',0),
			'addtohome_actions' 		=> (variable_get('addtohome_actions',0)) ? TRUE : FALSE,
			'addtohome_second_time' 	=> (variable_get('addtohome_actions',0)) ? TRUE : FALSE,
			'addtohome_show_after' 		=> variable_get('addtohome_show_after',1),
			'addtohome_lifespan' 		=> variable_get('addtohome_lifespan',15),
			'addtohome_display_pace' 	=> variable_get('addtohome_display_pace',1440),
			'addtohome_message' 		=> variable_get('addtohome_message',t("You can add a bookmark to your home screen.")),
			'addtohome_detect' 			=> (variable_get('addtohome_detect',0)) ? TRUE : FALSE,
			'addtohome_andr_message' 	=> variable_get('addtohome_andr_message',t("Install our application from Google Play")),
			'addtohome_andr_link' 		=> variable_get('addtohome_andr_link',"http://"),
			'addtohome_ios_icon' 		=> variable_get('addtohome_ios_icon',""),
			'path'						=> $path,
			'image_paths' 				=> $image_paths,
			'addtohome_ios_use_msgbox'	=> variable_get('addtohome_ios_use_msgbox',0),
			'addtohome_show_one_time' 	=> (variable_get('addtohome_show_one_time',0)) ? TRUE : FALSE,
		);
		
		drupal_add_js(array('addToHome'=>$my_settings),'setting');
		drupal_add_css($path.'/addtohomescreen.css','theme');
		drupal_add_js($path.'/addtohomescreen.min.js','theme');
		drupal_add_js($path.'/addtohomescreen_script.js','theme');
	}
	
}

function addtohome_check_num($element,&$form_state){
	if(!is_numeric($element['#value'])){
		form_set_error($element ,t("You have entered not a integer"));
	}
	if($element['#value'] < 0){
		form_set_error($element ,t("You have entered negative number"));
	}
}


function _get_file_path($fid){
    $paths = array();
	$query = "SELECT fid, filename, filepath, filesize, filemime  FROM {files} WHERE fid = %d";
	$result = db_query($query, $fid); 
	$paths = db_fetch_object($result);
	return $paths;
}


function _get_multiple_file_path($fids){
    $paths = array();
    $paths_result = array();
	$query = "	SELECT fid, filename, filepath, filesize, filemime  
				FROM {files} WHERE fid IN ( ". db_placeholders(array_values($fids),'int') ." )";
	$result = db_query($query,array_values($fids)); 
	$keys = array_keys($fids);
	
  	while ($row = db_fetch_object($result)) {
    	$paths[$row->fid] = $row;
    	//$paths[$row->fid][] = array_keys($fids,$row->fid); 
  	}
  	foreach ($fids as $key => $val) {
  		if($val){
  			$paths_result[$key] = $paths[$val]->filepath;
  		}else{
  			$paths_result[$key] = NULL;
  		}
  	}
	return $paths_result;
}

function addMeta($x, $size){
    $output = "";
    if($x!=NULL){
      	if($size!='0'){
        	$output.= "<link rel='apple-touch-icon' sizes='{$size}x{$size}' href='{$GLOBALS['base_path']}{$x}'>";
      	}else{
        	$output.= "<link rel='apple-touch-icon' href='{$GLOBALS['base_path']}{$x}'>";
      	}
    }
    
    return $output;
}