<?php
	//display help and module information
	function addtohome_help($path,$arg){
		$output = '';
		switch($path){
			case "admin/help#addtohome":
				$output = '<p>'.t("Create some features related to mobile phones").'</p>';
			break;
		}
		return $output;
	}


	//giving permissions
	function addtohome_perm(){
		return array('access addtohome content');
	}

	/**
	* Implementation of hook_block().
 	* @param string $op one of "list", "view", "save" and "configure"
 	* @param integer $delta code to identify the block
 	* @param array $edit only for "save" operation
	*/

	function addtohome_block($op = 'list',$delta = 0, $edit = array()){
		$block = array();
		switch ($op) {
			case 'list':
				$block[0]["info"] = t("Add to home screen"); 
				break;
			case 'view':
				break;
			case 'save':
				break;
			case 'configure':
				break;
		}
		return $block;
	}

	function addtohome_admin(){
		//array of file fids in order to use it in gettinf file's object
		$file_fids = variable_get('mobilesupport_icons',NULL);
		
		$form = array();
		$form['app_name'] = array(
			'#type' => 'textfield',
			'#title'=>t("Name of application"),
			'#default_value'=>variable_get('app_name','Application'),
			'#size'=>13,
			'#weight'=>1,
			'#max_length'=>11,
			'#description' => t("The name of application which user will see by default, but will can to change (max 11 letters)"),
			'#required'=>TRUE,
		);
		$form['ios']=array(
			'#type'=>'fieldset',
			'#title'=>t('IOS settings'),
			'#weight'=>5,
			'#collapsible'=>TRUE,
			'#collapsed'=>FALSE,
		);
			
			$form['ios']['display_times'] = array(
				'#type' => 'textfield',
				'#title'=>t("absolute maximum number of times the message will be shown to the user"),
				'#default_value'=>variable_get('display_times',0),
				'#size'=>13,
				'#max_length'=>10,
				'#description' => t("0: no limit"),
				'#required'=>TRUE,

			);
			$form['ios']['actions'] = array(
				'#type' => 'checkbox',
				'#title'=>t("Forbid actions before user closes window"),
				'#default_value'=>variable_get('actions',0),
				'#description' => t(""),
				'#required'=>TRUE,
			);
			$form['ios']['second_time'] = array(
				'#type' => 'checkbox',
				'#title'=>t("Doesn't show window first time, only second"),
				'#default_value'=>variable_get('second_time',0),
				'#description' => t("By default user sees window when enter the site first time"),
				'#required'=>TRUE,
			);
			$form['ios']['show_after'] = array(
				'#type' => 'textfield',
				'#title'=>t("Display the message after that many seconds from page load"),
				'#default_value'=>variable_get('show_after',1),
				'#size'=>13,
				'#max_length'=>10,
				'#required'=>TRUE,
			);
			$form['ios']['lifespan'] = array(
				'#type' => 'textfield',
				'#title'=>t("How many seconds window lives if user doesn't close it"),
				'#default_value'=>variable_get('lifespan',20),
				'#size'=>13,
				'#max_length'=>10,
				'#required'=>TRUE,
			);
			$form['ios']['display_pace'] = array(
				'#type' => 'textfield',
				'#title'=>t("Minutes before the message is shown again"),
				'#default_value'=>variable_get('display_pace',1440),
				'#size'=>13,
				'#max_length'=>10,
				'#description' => t("0: display every time, default 24 hours"),
				'#required'=>TRUE,
			);
			$form['ios']['message'] = array(
				'#type' => 'textfield',
				'#title'=>t("Message to appear"),
				'#default_value'=>variable_get('message',t("you can add a bookmark to you home screen")),
				'#size'=>60,
				'#max_length'=>60,
				'#description' => t("What will user see on this tooltip (max 60 letters)"),
				'#required'=>TRUE,


			);
			$form['ios']['detect'] = array(
				'#type' => 'checkbox',
				'#title'=>t("Try to detect if the site has been added to the homescreen"),
				'#default_value'=>variable_get('detect',0),
			);
			$form['ios']['ios_icon']=array(
				'#type' => 'file',
				'#title'=>t("An icon which user will see in message"),
			);
			//if file was uploaded
			if ($file_fids['ios_icon']){
				$file = _get_file_path($file_fids['ios_icon']);
				$form['ios']['ios_icon_link'] = array(
					'#value' => l(t('Current icon'), file_create_url($file->filepath),array('attributes'=>array('target'=>'_blank','external'=>TRUE))),
				);
				$form['ios']['delete_ios_icon']=array(
					'#type' => 'checkbox',
					'#title'=>t("Delete this icon"),
					'#default_value'=>variable_get('delete_ios_icon',0),
				);
				if(module_exists("imagecache")){
					$form['ios']['ios_icon']['#suffix'] = '<div>' . theme('imagecache', 'thumbnail', $file->filepath) . '</div>';
				}
			}
			
			$form['ios']['ios_ipad_icon']=array(
				'#type' => 'file',
				'#title'=>t("Ipad icon"),
				'#description' => "76x76",
			);
			//if file was uploaded
			if ($file_fids['ios_ipad_icon']){
				$file = _get_file_path($file_fids['ios_ipad_icon']);
				$form['ios']['ios_ipad_icon_link'] = array(
					'#value' => l(t('Current icon'), file_create_url($file->filepath),array('attributes'=>array('target'=>'_blank','external'=>TRUE))),
				);
				$form['ios']['delete_ios_ipad_icon']=array(
					'#type' => 'checkbox',
					'#title'=>t("Delete this icon"),
					'#default_value'=>variable_get('delete_ios_ipad_icon',0),
				);
				if(module_exists("imagecache")){
					$form['ios']['ios_ipad_icon']['#suffix'] = '<div>' . theme('imagecache', 'thumbnail', $file->filepath) . '</div>';
				}
			}


			$form['ios']['ios_iphone_retina']=array(
				'#type' => 'file',
				'#title'=>t("Iphone retina"),
				'#description' => "120x120",
			);
			//if file was uploaded
			if ($file_fids['ios_iphone_retina']){
				$file = _get_file_path($file_fids['ios_iphone_retina']);
				$form['ios']['ios_iphone_retina_link'] = array(
					'#value' => l(t('Current icon'), file_create_url($file->filepath),array('attributes'=>array('target'=>'_blank','external'=>TRUE))),
				);
				$form['ios']['delete_ios_iphone_retina']=array(
					'#type' => 'checkbox',
					'#title'=>t("Delete this icon"),
					'#default_value'=>variable_get('delete_ios_iphone_retina',0),
				);
				if(module_exists("imagecache")){
					$form['ios']['ios_iphone_retina']['#suffix'] = '<div>' . theme('imagecache', 'thumbnail', $file->filepath) . '</div>';
				}
			}


			$form['ios']['ios_ipad_retina']=array(
				'#type' => 'file',
				'#title'=>t("Ipad retina"),
				'#description' => "152x152",
			);
			//if file was uploaded
			if ($file_fids['ios_ipad_retina']){
				$file = _get_file_path($file_fids['ios_ipad_retina']);
				$form['ios']['ios_ipad_retina_link'] = array(
					'#value' => l(t('Current icon'), file_create_url($file->filepath),array('attributes'=>array('target'=>'_blank','external'=>TRUE))),
				);
				
				if(module_exists("imagecache")){
					$form['ios']['ios_ipad_retina']['#suffix'] = '<div>' . theme('imagecache', 'thumbnail', $file->filepath) . '</div>';
				}
				$form['ios']['delete_ios_ipad_retina']=array(
					'#type' => 'checkbox',
					'#title'=>t("Delete this icon"),
					'#default_value'=>variable_get('delete_ios_ipad_retina',0),
				);
			}



		$form['android']=array(
			'#type'=>'fieldset',
			'#title'=>t('Android settings'),
			'#weight'=>4,
			'#collapsible'=>TRUE,
			'#collapsed'=>FALSE,
		);
			$form['android']['andr_message']=array(
				'#type' => 'textfield',
				'#title'=>t("Message to appear"),
				'#default_value'=>variable_get('andr_message',t("Install our application from Android Playmarket")),
				'#size'=>60,
				'#max_length'=>60,
			);
			$form['android']['andr_link']=array(
				'#type' => 'textfield',
				'#title'=>t("Link to Android Playmarket"),
				'#default_value'=>variable_get('andr_link',"http://"),
				'#size'=>60,
				'#max_length'=>60,

			);
			$form['android']['and_icon']=array(
				'#type' => 'file',
				'#title'=>t("An icon which user will see in message"),
			);
			//if file was uploaded
			if ($file_fids['and_icon']){
				$file = _get_file_path($file_fids['and_icon']);
				$form['android']['and_icon_link'] = array(
					'#value' => l(t('Current icon'), file_create_url($file->filepath),array('attributes'=>array('target'=>'_blank','external'=>TRUE))),
				);
				
				if(module_exists("imagecache")){
					$form['android']['and_icon']['#suffix'] = '<div>' . theme('imagecache', 'thumbnail', $file->filepath) . '</div>';
				}
				$form['android']['delete_and_icon']=array(
					'#type' => 'checkbox',
					'#title'=>t("Delete this icon"),
					'#default_value'=>variable_get('delete_and_icon',0),
				);
			}
		$form['#attributes'] = array('enctype' => "multipart/form-data");
		$form['#submit'][] = 'addtohome_submit';
			 
		return system_settings_form($form);
	}

function addtohome_menu(){
	$items = array();
	$items['admin/settings/addtohome'] = array(
		'title' => t('Module settings'),
		'description' => 'description',
		'page callback' =>'drupal_get_form',
		'page arguments' => array('addtohome_admin'),
		'access arguments' => array('administer addtohome settings'),
		'type'=> MENU_NORMAL_ITEM,

	);
	return $items;
}

function addtohome_admin_validate($form, &$form_state){
	// file_save_upload
	$name_dir = "mobilesupport";
	$dir = file_directory_path() . DIRECTORY_SEPARATOR . $name_dir;
		
	$file_fids = variable_get('mobilesupport_icons', array());
	
	if(file_check_directory($dir, FILE_CREATE_DIRECTORY)){
		
		//delete file according to user request
		if($form_state['values']['delete_ios_icon']==1 && $file_fids['ios_icon']){
			$filepath =  _get_file_path($file_fids['ios_icon'])->filepath;
			file_delete($filepath);
			// put value of NULL in order not to obtain image
			$file_fids['ios_icon'] = NULL;
			//turn the flag of delete to 0
			$form_state['values']['delete_ios_icon']=0;


		}
		if($form_state['values']['delete_ios_ipad_icon']==1 && $file_fids['ios_ipad_icon']){
			$filepath =  _get_file_path($file_fids['ios_ipad_icon'])->filepath;
			file_delete($filepath);
			$file_fids['ios_ipad_icon'] = NULL;
			$form_state['values']['delete_ios_ipad_icon']=0;
			

		}
		if($form_state['values']['delete_ios_ipad_retina']==1 && $file_fids['ios_ipad_retina']){
			$filepath =  _get_file_path($file_fids['ios_ipad_retina'])->filepath;
			file_delete($filepath);
			$file_fids['ios_ipad_retina'] = NULL;
			$form_state['values']['delete_ios_ipad_retina']=0;

		}
		if($form_state['values']['delete_ios_iphone_retina']==1 && $file_fids['ios_iphone_retina']){
			$filepath =  _get_file_path($file_fids['ios_iphone_retina'])->filepath;
			file_delete($filepath);
			$file_fids['ios_iphone_retina'] = NULL;
			$form_state['values']['delete_ios_iphone_retina']=0;

		}
		if($form_state['values']['delete_and_icon']==1 && $file_fids['and_icon']){
			$filepath =  _get_file_path($file_fids['and_icon'])->filepath;
			file_delete($filepath);
			$file_fids['and_icon'] = NULL;
			$form_state['values']['delete_and_icon']=0;

		}




		$cus_file = file_save_upload('ios_icon',array(),$dir);
		if($cus_file){
			file_set_status($cus_file, FILE_STATUS_PERMANENT);
			drupal_write_record('files', $cus_file, 'fid');
			if ($file_fids['ios_icon']) {
				//delete file
				$filepath =  _get_file_path($file_fids['ios_icon'])->filepath;
				file_delete($filepath);
			}
			$file_fids['ios_icon'] = $cus_file->fid;
		}
		
		$cus_file = file_save_upload('ios_ipad_icon',array(),$dir);
		if($cus_file){
			file_set_status($cus_file, FILE_STATUS_PERMANENT);
			drupal_write_record('files', $cus_file, 'fid');
			if ($file_fids['ios_ipad_icon']) {
				//delete file 
				file_delete($cus_file->filepath);	
			}
			$file_fids['ios_ipad_icon'] = $cus_file->fid;
		}

		$cus_file = file_save_upload('ios_ipad_retina',array(),$dir);
		if($cus_file){
			file_set_status($cus_file, FILE_STATUS_PERMANENT);
			drupal_write_record('files', $cus_file, 'fid');
			if ($file_fids['ios_ipad_retina']) {
				//delete file 
				file_delete($cus_file->filepath);	
			}
			$file_fids['ios_ipad_retina'] = $cus_file->fid;
		}

		$cus_file = file_save_upload('ios_iphone_retina',array(),$dir);
		if($cus_file){
			file_set_status($cus_file, FILE_STATUS_PERMANENT);
			drupal_write_record('files', $cus_file, 'fid');
			if ($file_fids['ios_iphone_retina']) {
				//delete file 
				file_delete($cus_file->filepath);
				
			}
			$file_fids['ios_iphone_retina'] = $cus_file->fid;
		}

		$cus_file = file_save_upload('and_icon',array(),$dir);
		if($cus_file){
			file_set_status($cus_file, FILE_STATUS_PERMANENT);
			drupal_write_record('files', $cus_file, 'fid');
			if ($file_fids['and_icon']) {
				//delete file 
				file_delete($cus_file->filepath);
				
			}
			$file_fids['and_icon'] = $cus_file->fid;
		} 
	}

	variable_set('mobilesupport_icons', $file_fids);

	//validation
	checkInt($form_state['values']['display_times'],'display_times');
	checkPos($form_state['values']['display_times'],'display_times');

	checkInt($form_state['values']['show_after'],'show_after');
	checkPos($form_state['values']['show_after'],'show_after');

	checkInt($form_state['values']['lifespan'],'lifespan');
	checkPos($form_state['values']['lifespan'],'lifespan');

	checkInt($form_state['values']['display_pace'],'display_pace');
	checkPos($form_state['values']['display_pace'],'display_pace');

	if(!valid_url($form_state['values']['andr_link'])){
		form_set_error('andr_link' ,t("You have entered an incorrect link"));
	}

	//clear strings
	variable_set('app_name',check_plain($form_state['values']['app_name']));
	variable_set('message',check_plain($form_state['values']['message']));
	variable_set('andr_message',check_plain($form_state['values']['andr_message']));
}


function addtohome_init(){
	if(drupal_is_front_page()){
		$path = drupal_get_path('module','addtohome');
		//get path to images
		$image_fids = variable_get('mobilesupport_icons',NULL);
		$image_paths = array();
		if($image_fids){
			foreach ($image_fids as $key => $val) {
				if($val){
					$res = _get_file_path($val);
					$image_paths[$key] = $res->filepath;
					
				}else{
					$image_paths[$key] = NULL;
				}
			}
		}
		//create an array of settings to send it o js
		$my_settings = array(
			'app_name' => variable_get('app_name','Application'),
			'display_times' => variable_get('display_times',0),
			'actions' => (variable_get('actions',0)) ? TRUE : FALSE,
			'second_time' => (variable_get('actions',0)) ? TRUE : FALSE,
			'show_after' => variable_get('show_after',1),
			'lifespan' => variable_get('lifespan',15),
			'display_pace' => variable_get('display_pace',1440),
			'message' => variable_get('message',t("You can add a bookmark to you home screen.")),
			'detect' => (variable_get('detect',0)) ? TRUE : FALSE,
			'andr_message' => variable_get('andr_message',t("Install our application from Android Play market")),
			'andr_link' => variable_get('andr_link',"http://"),
			'ios_icon' =>variable_get('ios_icon',""),
			'path'=>$path,
			'image_paths' => $image_paths,
		);
		
		drupal_add_js(array('addToHome'=>$my_settings),'setting');
		drupal_add_css($path.'/addtohomescreen.css','theme');
		drupal_add_js($path.'/addtohomescreen.min.js','theme');
		drupal_add_js($path.'/addtohomescreen_script.js','theme');
	}
	
}

function checkInt($x,$y){
	if(!is_numeric($x)){
		form_set_error($y ,t("You have entered not a integer"));
	}
}

function checkPos($x,$y){
	if($x<0){
		form_set_error($y ,t("You have entered negative number"));
	}
}

function _get_file_path($fid){
	$query = "SELECT fid, filename, filepath, filesize, filemime  FROM {files} WHERE fid = %d";
	$result = db_query($query, $fid);
	return db_fetch_object($result);
}